namespace=wtms
dockerRegistry=https://docker-registry.default.svc:5000
image=docker-registry.default.svc:5000/wtms/rept
selector=rept
appname=rept
isIpcRunningEnv=true
isEpcRunningEnv=false
apiKey=d614045bc195449ebc749287c54a306b
projectId=356